version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "remove-bg-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1um1ihig2uppy"
s3_prefix = "remove-bg-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
