AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  remove-bg-serverless

  Serverless Template for calling the remove.bg API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RemoveBgServerlessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: remove-bg-serverless/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          REMOVEBG_API_KEY: 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RemoveBgServerlessFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RemoveBgServerlessFunctionFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RemoveBgServerlessFunction.Arn
  RemoveBgServerlessFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RemoveBgServerlessFunction.Arn
